version: "3.9"
x-amigos-common:
  &amigos-common
  deploy:
    resources:
      limits:
        memory: 200m
  restart: always
  network_mode: host

x-amigos-backend-common:
  &amigos-backend-common
  <<: *amigos-common
  env_file:
    - ./backend/.env

services:
  backend:
    <<: *amigos-backend-common
    build: 
      context: ./backend/.
      dockerfile: ./Dockerfile
    expose:
      - 8000
    volumes:
      - ./backend/:/app
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    <<: *amigos-backend-common
    container_name: postgres
    image: postgres:14.1-alpine
    volumes:
      - postgres-db:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "amigos-dev"]
      interval: 5s
      retries: 5

volumes:
  postgres-db: