@HOST=http://127.0.0.1:8000/auth
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3J2aWRhbDU4NEBnbWFpbC5jb20iLCJleHAiOjE2NTg3ODEwOTR9.fGjSq9GXGIFisR63kNnxoId3idYQ0XFo4NQMU2OUnQs


### GET Auth check
GET {{HOST}}/check
Authorization: Bearer {{TOKEN}}


### POST Get Access Token
POST {{HOST}}/token
Content-Type: application/json

{
    "username": "victorvidal584@gmail.com",
    "password": "123"
}


### Post Create Recovery Number
POST {{HOST}}/create_recovery_number
Content-Type: application/json

{
    "email": "victorvidal584@gmail.com"
}


### Post Check Recovery Number
POST {{HOST}}/check_recovery_number
Content-Type: application/json

{
    "email": "victorvidal584@gmail.com",
    "number": 7914
}