@HOST=http://127.0.0.1:8000/auth

### POST Get Access Token
POST {{HOST}}/token
Content-Type: application/x-www-form-urlencoded

&username=victorvidal584@gmail.com
&password=098


### Post Create Recovery Number
POST {{HOST}}/create_recovery_number
Content-Type: application/json

{
    "email": "victorvidal584@gmail.com"
}


### Post Check Recovery Number
POST {{HOST}}/check_recovery_number
Content-Type: application/json

{
    "email": "victorvidal584@gmail.com",
    "number": 7914
}