@HOST=http://127.0.0.1:8000/complaints
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3J2aWRhbDU4NEBnbWFpbC5jb20iLCJleHAiOjE2NTg2OTI1MTZ9.VtnsmoudbX1i__3JtIxaRjA6Xom6dBnWpnUcKPcTl-A

### GET Complaint Categories
GET {{HOST}}/categories
Authorization: Bearer {{TOKEN}}


### GET Complaints
GET {{HOST}}/
Authorization: Bearer {{TOKEN}}


### GET Complaints
POST {{HOST}}/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "owner_id": "aea40498-b66e-4a81-b265-bdac71eaf4bc",
    "category_id": "9de3cb7d-b650-499d-8d5a-3e40a75033ab",
    "title": "Falta de rampa de acesso",
    "latitude": 15.2,
    "longitude": 20.0
}


### GET Complaint
GET {{HOST}}/7909372e-8533-486b-b836-403154ded70b/
Authorization: Bearer {{TOKEN}}