@HOST=http://127.0.0.1:8000/users
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ2aWN0b3J2aWRhbDU4NEBnbWFpbC5jb20iLCJleHAiOjE2NjEyMDY1MjF9.Bh31JUNxF2U8F5lopSE75aPy6jFHkKSggDd1Wlt4PMg

### Get me
GET {{HOST}}/me/
Authorization: Bearer {{TOKEN}}

### Get Users
GET {{HOST}}/
Authorization: Bearer {{TOKEN}}

### Get User
GET {{HOST}}/aea40498-b66e-4a81-b265-bdac71eaf4bc/
Authorization: Bearer {{TOKEN}}


### Post User
POST {{HOST}}/
Content-Type: application/json

{
    "email": "barpo@gmail.com",
    "password": "123"
}


### Delete User
DELETE {{HOST}}/1a861673-78d2-4a73-bf33-ad305ddf5f84/
Authorization: Bearer {{TOKEN}}


### PATCH User
PATCH {{HOST}}/650b83ae-8389-43ba-aae7-54502bda6de2/
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
    "password": "098"
}